local priority = require("workflow-assistant.priority")

describe("priority", function()
  describe("is_valid", function()
    it("accepts none/low/normal/high/critical", function()
      assert.is_true(priority.is_valid("none"))
      assert.is_true(priority.is_valid("low"))
      assert.is_true(priority.is_valid("normal"))
      assert.is_true(priority.is_valid("high"))
      assert.is_true(priority.is_valid("critical"))
    end)

    it("rejects anything else", function()
      assert.is_false(priority.is_valid("urgent"))
      assert.is_false(priority.is_valid(nil))
    end)
  end)

  describe("meets", function()
    it("orders none < low < normal < high < critical", function()
      assert.is_false(priority.meets("low", "normal"))
      assert.is_true(priority.meets("normal", "normal"))
      assert.is_true(priority.meets("high", "normal"))
      assert.is_true(priority.meets("high", "low"))
      assert.is_false(priority.meets("normal", "high"))
      assert.is_false(priority.meets("none", "low"))
      assert.is_true(priority.meets("none", "none"))
      assert.is_true(priority.meets("critical", "high"))
      assert.is_false(priority.meets("high", "critical"))
      assert.is_true(priority.meets("critical", "critical"))
    end)

    it("treats an invalid/missing value as the default ('normal') on either side", function()
      assert.is_true(priority.meets(nil, nil))
      assert.is_true(priority.meets("bogus", "bogus"))
      assert.is_false(priority.meets("low", nil)) -- low < normal (the default)
    end)
  end)
end)
